version: "3.8"

services:
  postgres_db:
    image: postgres:12
    container_name: tennis_postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./sql:/sql/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    env_file:
      - ./.env
    ports:
      - 5433:5432
  redis:
    image: redis:alpine
    container_name: tennis_redis
  web:
    build: .
    container_name: tennis_django
    command: bash -c "python manage.py test && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8002:8000
    environment:
      - DJANGO_DEBUG=True
    env_file:
      - ./.env
    depends_on:
      - redis
  bot:
    build: .
    container_name: tennis_bot
    command: ipython player_bot/main.py
    env_file:
      - ./.env
    depends_on:
      - web
  admin_bot:
    build: .
    container_name: tennis_admin_bot
    command: ipython admin_bot/main.py
    env_file:
      - ./.env
    depends_on:
      - web
  parent_bot:
    build: .
    container_name: tennis_parent_bot
    command: ipython parent_bot/main.py
    env_file:
      - ./.env
    depends_on:
      - web
  celery:
    build: .
    container_name: tennis_celery
    command: celery -A tennis_bot worker --loglevel=INFO
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - redis
      - web
  celery-beat:
    build: .
    container_name: tennis_celery_beat
    command: celery -A tennis_bot beat --loglevel=INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - redis
      - celery
      - web

volumes:
  postgres_data:
