PAYMENT_YEAR = 'PAYMENT_YEAR'
PAYMENT_YEAR_MONTH = 'PAY_YEAR_MN'
PAYMENT_YEAR_MONTH_GROUP = 'PAY_YR_MN_GR'
PAYMENT_START_CHANGE = 'PAY_START_CHANGE'

PAYMENT_CONFIRM_OR_CANCEL = 'CNF_OR_CNCL'
PAYMENT_CHANGE_YES = 'YES'
PAYMENT_CHANGE_NO = 'NO'
