PAYMENT_YEAR = 'PAYMENT_YEAR'
PAYMENT_YEAR_MONTH = 'PAY_YEAR_MN'
PAYMENT_YEAR_MONTH_GROUP = 'PAY_YR_MN_GR'
PAYMENT_START_CHANGE = 'PAY_START_CHANGE'
PAYMENT_CONFIRM_OR_CANCEL = 'CNF_OR_CNCL'

SEND_MESSAGE = 'SND_MSG'

SELECT_DAY_TO_SHOW_COACH_SCHEDULE = 'COACH_SCHEDULE'
SHOW_GROUPDAY_INFO = 'GROUPDAY_INFO'

SET_UP_TIME_BEFORE_CANCEL_BUTTON = 'TIME_BEFORE_CANCEL'
SET_UP_PLAYER_STATUS = 'PLAYER_STATUS'

SELECT_SKIP_TIME_BUTTON = 'SELECT_SKIP_TIME'
SHOW_INFO_ABOUT_SKIPPING_DAY = 'INFO_SKIPPING_DAY'

SELECT_TRAINING_TYPE = 'SELECT_TRAINING_TYPE'

SELECT_GROUP_LESSON_TIME = 'SELECT_GROUP_LESSON'
SELECT_PRECISE_GROUP_TIME = 'SELECT_PRECISE_GROUP_TIME'
CONFIRM_GROUP_LESSON = 'CONFIRM_GROUP'

SELECT_DURATION_FOR_IND_TRAIN = 'SELECT_DURATION_FOR_IND_TRAIN'
SELECT_IND_LESSON_TIME = 'SELECT_IND_LESSON_TIME'
SELECT_PRECISE_IND_TIME = 'IND_TIME'
PERMISSION_FOR_IND_TRAIN = 'PERMISSION_IND_TRAIN'
AMOUNT_OF_IND_TRAIN = 'AMOUNT_IND_TRAIN'

CLNDR_IGNORE = 'IGNORE'
CLNDR_DAY = "DAY"
CLNDR_PREV_MONTH = "PREV-MONTH"
CLNDR_NEXT_MONTH = "NEXT-MONTH"

CLNDR_ACTION_BACK = 'BACK'
CLNDR_ACTION_SKIP = 'SKIP'
CLNDR_ACTION_TAKE_GROUP = 'TAKE_GROUP'
CLNDR_ACTION_TAKE_IND = 'TAKE_IND'
CLNDR_ADMIN_VIEW_SCHEDULE = 'VIEW_SCHEDULE'

PAYMENT_VISITING = 'PMNT_VST'
PAYMENT_BONUS = 'bonus'
PAYMENT_MONEY = 'money'

