# Generated by Django 3.1.7 on 2021-04-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210405_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininggroup',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
