# Generated by Django 3.1.7 on 2021-04-10 07:52

from django.db import migrations, models


def insert_data_in_photo(apps, schema_editor):
    Photo = apps.get_model("base", "Photo")
    Photo.objects.update_or_create(
        url="https://perfum-online.by/image/data/1news/that-to-do-%D1%87%D1%82%D0%BE%D0%B1-not-to-miss-drills.jpg",
        text="Знаю, что лень идти, а надо. Сегодня тренировка:",
    )
    Photo.objects.update_or_create(
        url="https://i.pinimg.com/originals/9f/ce/af/9fceaf6c5518ec0526d0d2d86d8cfb01.jpg",
        text="А кто это у нас уже забыл о тренировке, а? Напоминаю:",
    )
    Photo.objects.update_or_create(
        url="https://ggym.ru/files/170215/art-lebedev.jpg",
        text="Терпение и труд всё перетрут, не забудь о тренировке:",
    )
    Photo.objects.update_or_create(
        url="https://i.pinimg.com/474x/80/0e/f0/800ef02d7823ffbb097449feb5825d44.jpg",
        text="Ой, а кто это уже забыл о тренировке? Напоминаю:",
    )
    Photo.objects.update_or_create(
        url="https://s-cdn.sportbox.ru/images/styles/690_388/fp_fotos/b9/05/2cfa2db501437ee9f77b96efa14d6c4e5fa6b7e2ce5c6291318978.jpg",
        text="Твой контракт с Lacoste уже близок, главное — не пропустить сегодняшнюю тренировку:",
    )
    Photo.objects.update_or_create(
        url="https://i.pinimg.com/736x/a3/48/34/a34834232790bc0528f460d977e2a296.jpg",
        text="Неужели вы похожи с этим человеком? Надеюсь, что нет. Сегодня тренировка:",
    )
    Photo.objects.update_or_create(
        url="https://newsomsk.ru/images/uploading/2a6ca712467a5fa4fd45031f85ab87b6.jpg",
        text="Какой прекрасный котик:) Не стань таким же, сегодня тренировка:",
    )
    Photo.objects.update_or_create(
        url="https://memepedia.ru/wp-content/uploads/2017/09/%D0%BD%D0%B5-%D0%BC%D0%BE%D0%B3%D1%83-%D0%BD%D0%B8%D1%87%D0%B5%D0%B3%D0%BE-%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D1%83-%D0%BC%D0%B5%D0%BD%D1%8F-%D0%BB%D0%B0%D0%BF%D0%BA%D0%B8.jpg",
        text="А ты можешь делать все, ведь у тебя есть ракетка! Сегодня тренировка:",
    )
    Photo.objects.update_or_create(
        url="https://sun9-47.userapi.com/jnrLYf7VsyWwM8NtbsriLmse5pFI22i_m6Tdlg/j37vKNL6OCs.jpg",
        text="Действительно, как это? Не забудь:",
    )
    Photo.objects.update_or_create(
        url="https://bookmaker-ratings.ru/wp-content/uploads/2016/06/Dzhok.jpg",
        text="Сегодня проходим новый удар, приходи.",
    )
    Photo.objects.update_or_create(
        url="https://i.pinimg.com/originals/1f/2c/fa/1f2cfa82c65df4138a4cf781b8f966e0.jpg",
        text="Постепенно превратишься в эту обезьянку, если не будешь ходить. Напоминаю:",
    )
    Photo.objects.update_or_create(
        url="https://doseng.org/uploads/posts/2011-01/1295577046_podborka_83.jpg",
        text="Еда для тех, кто пропускает тренировки. Не забудь сегодня:",
    )
    Photo.objects.update_or_create(
        url="http://tennispeople.ru/wp-content/uploads/2019/06/16-iyulya-741x1024.jpeg",
        text="Сегодня даже кошка тренируется, так что приходи.",
    )
    Photo.objects.update_or_create(
        url="https://shutniki.club/wp-content/uploads/2020/02/Prikoly_pro_tennis_15_02142004.jpg",
        text="Сегодня повторяем эту цитату, не забудь.",
    )
    Photo.objects.update_or_create(
        url="https://s3-eu-west-1.amazonaws.com/uploads.playbaamboozle.com/uploads/images/23164/1589396590_146414",
        text="Узнаешь? Ну ничего, труд из обезьяны сделал теннисиста.",
    )
    Photo.objects.update_or_create(
        url="https://demotivatorium.ru/sstorage/3/2013/08/12210417129067/demotivatorium_ru_to_samoe_chuvstvo_kogda_27757.jpg",
        text="Желаю тебе, чтобы ничего сегодня не защемило, приходи.",
    )
    Photo.objects.update_or_create(
        url="https://pbs.twimg.com/media/D9sbAfaWsAE_55P.jpg",
        text="Говорят, что это фото было сделано на том самом корте на Косой Горе. Приходи сегодня!",
    )
    Photo.objects.update_or_create(
        url="https://i.dailymail.co.uk/i/pix/2012/10/10/article-2215659-156FF0C5000005DC-190_964x500.jpg",
        text="Приходи сегодня! Специально для тебя Владлен сделает также.",
    )
    Photo.objects.update_or_create(
        url="http://fototelegraf.ru/wp-content/uploads/2010/12/luchshye-sportivnye-foto-21-25.jpg",
        text="Сегодня Владлен добавляет 5 отыгрышей тем, кто отобьёт также, так что приходи.",
    )
    Photo.objects.update_or_create(
        url="https://cdn.fishki.net/upload/post/2016/09/21/2080507/1-f-50224.jpg",
        text="Никто не может выиграть у Владлена один раз подряд. Приходи сегодня, попробуй!",
    )
    Photo.objects.update_or_create(
        url="https://golf.com/wp-content/uploads/2019/04/114_May_Travel_GolfTown-1-1.jpg",
        text="Если придешь сегодня, то @ta2asho подберёт тебе кроссовки от легендарного теннисиста Stan Smith.",
    )
    Photo.objects.update_or_create(
        url="https://i.pinimg.com/736x/53/88/20/53882082be0a29f30748db86f53b9398.jpg",
        text="Не обижай мячик сегодня.",
    )
    Photo.objects.update_or_create(
        url="https://shutniki.club/wp-content/uploads/2020/02/Prikoly_pro_tennis_8_02142000.jpg",
        text="Сегодня по расписанию у нас средний теннис.",
    )
    Photo.objects.update_or_create(
        url="https://kaifolog.ru/uploads/posts/2012-04/1335357965_003.jpg",
        text="Сегодня Владен не откажет, если ты попросишь повторить его это.",
    )
    Photo.objects.update_or_create(
        url="https://www.si.com/.image/t_share/MTY4MjU5MjE5MjI3OTQ0ODMz/andy-murray-blogjpg.jpg",
        text="Сегодня на разминке делаем следующее упражнение.",
    )
    Photo.objects.update_or_create(
        url="https://i02.fotocdn.net/s107/051ba57737d5ed57/public_pin_l/2357071112.jpg",
        text="Захвати сегодня на тренировку арбузика:)",
    )
    Photo.objects.update_or_create(
        url="https://www.tennismagazin.de/content/uploads/2016/02/gettyimages-112177891.jpg",
        text="Сегодня на тренировке без сломанных ракеток, пожалуйста.",
    )
    Photo.objects.update_or_create(
        url="https://joker.ykt.ru/uploads/posts/1329914517_1367_21.02.2012.jpeg",
        text="Сегодня на тренировке вся группа становится в ряд и делает дзынь-дзынь.",
    )
    Photo.objects.update_or_create(
        url="https://tunnel.ru/media/images/2016-09/post_comment/739962/at736833740.jpg",
        text="Поработаем сегодня над растяжкой, приходи!",
    )
    Photo.objects.update_or_create(
        url="http://img0.joyreactor.cc/pics/post/full/%D0%B4%D0%B5%D0%B2%D1%83%D1%88%D0%BA%D0%B0-%D0%B2%D0%BE%D0%BB%D0%BE%D1%81%D0%B0%D1%82%D0%B0%D1%8F-%D1%82%D0%B5%D0%BD%D0%BD%D0%B8%D1%81-%D0%BF%D0%B5%D1%81%D0%BE%D1%87%D0%BD%D0%B8%D1%86%D0%B0-750982.jpeg",
        text="Иногда на улице холодно. Как же хорошо, что на корте тепло, приходи сегодня!",
    )
    Photo.objects.update_or_create(
        url="http://i1.tiesraides.lv/0x0/galleries/valdis_berzins/4c8b0faa90af5/2010-09-11_11.jpg",
        text="Ноготочки все покрасили? Сегодня проверяем. Кто не покрасил, у того -1 отыгрыш.",
    )
    Photo.objects.update_or_create(
        url="https://mtdata.ru/u28/photo80D4/20019914451-0/original.jpg",
        text="Сегодня будет больше мужского или женского тенниса?",
    )
    Photo.objects.update_or_create(
        url="https://301-1.ru/uploads/image/rostov-smog-smozhesh-i-ty_Ti0bxWmuMD.jpg",
        text="Согласен. Напоминаю:",
    )
    Photo.objects.update_or_create(
        url="https://klike.net/uploads/posts/2019-09/1567333956_2.jpg",
        text="Но а пока мы все ещё котики. Напоминаю:",
    )
    Photo.objects.update_or_create(
        url="https://www.anekdotovmir.ru/wp-content/uploads/2017/05/%D0%B0%D0%BD%D0%B5%D0%BA%D0%B4%D0%BE%D1%82-%D0%BF%D1%80%D0%BE-%D1%82%D0%B5%D0%BD%D0%BD%D0%B8%D1%81.jpg",
        text="Сегодня Владлен принесет свой ковёр, нужно помочь.",
    )
    Photo.objects.update_or_create(
        url="https://qph.fs.quoracdn.net/main-qimg-d58bd9d0e09aadddf367cd84b1b8c01b.webp",
        text="Сегодня тренируем телепатию.",
    )
    Photo.objects.update_or_create(
        url="https://i.pinimg.com/236x/e8/c6/96/e8c6967e78de73e2ede88d6552f32baf--tennis-funny-tennis-memes.jpg",
        text="Сегодня фотографируем твоё лицо во время удара.",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_traininggroup_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ссылка на картинку"
                    ),
                ),
                (
                    "telegram_id",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="id картинки на сервере телеграма",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True, null=True, verbose_name="Текстовое описание"
                    ),
                ),
            ],
            options={"verbose_name": "фотография", "verbose_name_plural": "фотографии"},
        ),
        migrations.RunPython(insert_data_in_photo),
    ]
