# Generated by Django 3.2 on 2021-04-27 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouptrainingday",
            name="pay_bonus_visitors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Платный отыгрыш",
                related_name="pay_bonus_visitors",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Заплатили ₽ + отыгрыш",
            ),
        ),
    ]
