# Generated by Django 3.2.4 on 2021-10-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_grouptrainingday_pay_bonus_visitors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininggroup',
            name='available_for_additional_lessons',
            field=models.BooleanField(default=False, help_text='Можно ли прийти в эту группу на занятия за деньги, если меньше, чем max_players', verbose_name='Занятия за деньги'),
        ),
        migrations.AlterField(
            model_name='traininggroup',
            name='level',
            field=models.CharField(choices=[('G', '🟢зелёный мяч🟢'), ('O', '🟠оранжевый мяч🟠')], default='O', max_length=1, verbose_name='Уровень группы'),
        ),
        migrations.AlterField(
            model_name='traininggroup',
            name='status',
            field=models.CharField(choices=[('I', 'для индивидуальных тренировок'), ('R', 'для аренды корта'), ('G', 'взрослые групповые тренировки'), ('F', 'детская группа малой численности'), ('S', 'детская секция')], default='G', max_length=1, verbose_name='Статус группы'),
        ),
    ]
