# Generated by Django 3.2.4 on 2021-11-15 21:43

import datetime
from django.db import migrations, models
import uuid


def insert_data_from_users_to_players(apps, schema_editor):
    Player = apps.get_model('base', 'Player')
    User = apps.get_model('base', 'User')

    for user in User.objects.all().iterator():
        Player.objects.create(
            first_name=user.first_name,
            last_name=user.last_name,
            phone_number=user.phone_number,
            tg_id=user.id,
            tg_username=user.telegram_username,
            has_blocked_bot=user.is_blocked,
            status=user.status,
            time_before_cancel=user.time_before_cancel,
            bonus_lesson=user.bonus_lesson,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20211030_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=32, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=32, null=True, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=16, null=True, verbose_name='Номер телефона')),
                ('tg_id', models.PositiveBigIntegerField(verbose_name='telegram id')),
                ('tg_username', models.CharField(blank=True, max_length=64, null=True)),
                ('has_blocked_bot', models.BooleanField(default=False, verbose_name='заблокировал бота')),
                ('deep_link', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('W', 'в ожидании'), ('G', 'групповые тренировки'), ('A', 'свободный график'), ('F', 'закончил')], default='W', max_length=1, verbose_name='статус')),
                ('time_before_cancel', models.DurationField(default=datetime.timedelta(seconds=21600), help_text='ЧАСЫ:МИНУТЫ:СЕКУНДЫ', null=True, verbose_name='Время, за которое нужно предупредить')),
                ('bonus_lesson', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Количество отыгрышей')),
            ],
            options={
                'verbose_name': 'игрок',
                'verbose_name_plural': 'игроки',
            },
        ),
        migrations.RunPython(insert_data_from_users_to_players)
    ]
