# Generated by Django 3.2.4 on 2021-11-15 21:52

from django.db import migrations, models


def insert_players_from_users(apps, schema_editor):
    Player = apps.get_model('base', 'Player')
    TrainingGroup = apps.get_model('base', 'TrainingGroup')

    for group in TrainingGroup.objects.all().iterator():
        users_tg_ids = list(group.users.all().values_list('id', flat=True))
        players = Player.objects.filter(tg_id__in=users_tg_ids)
        group.players.add(*players)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_create_players_from_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininggroup',
            name='players',
            field=models.ManyToManyField(to='base.Player'),
        ),
        migrations.RunPython(insert_players_from_users)
    ]
