# Generated by Django 3.2.4 on 2021-11-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_insert_players_from_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininggroup',
            name='players',
            field=models.ManyToManyField(to='base.Player'),
        ),
    ]
