# Generated by Django 3.2.4 on 2021-11-16 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_from_users_to_players'),
    ]

    operations = [
        migrations.RunSQL("delete from django_admin_log;"),
        migrations.DeleteModel(
            name='User',
        ),
    ]
