# Generated by Django 3.2.4 on 2021-11-20 14:56

from django.db import migrations, models


def rm_non_admin_users(apps, schema_editor):
    User = apps.get_model('base', 'User')
    User.objects.exclude(is_superuser=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_rm_tmp_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='parent',
        ),
        migrations.AlterField(
            model_name='grouptrainingday',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Будет ли в этот день тренировка у этой группы',
                                      verbose_name='Доступно'),
        ),
        migrations.AlterField(
            model_name='traininggroup',
            name='max_players',
            field=models.SmallIntegerField(default=6, verbose_name='Макс. игроков'),
        ),
        migrations.RunPython(rm_non_admin_users),
    ]
