# Generated by Django 3.2.4 on 2021-12-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_player_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='max_lessons_for_bonus_in_future',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Ограничение на кол-во тренировок за отыгрыши'),
        ),
    ]
