# Generated by Django 3.2.4 on 2021-12-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_player_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_parent',
            field=models.BooleanField(default=False, help_text='является ли игрок родителем и имеет доступ к родительскому боту', verbose_name='Родитель ли'),
        ),
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('W', 'в ожидании'), ('G', 'групповые тренировки'), ('A', 'свободный график'), ('F', 'закончил')], default='W', max_length=1, verbose_name='статус'),
        ),
    ]
