# Generated by Django 3.2.4 on 2022-02-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0021_ind_status_for_tr_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouptrainingday",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
