# Generated by Django 2.0.5 on 2020-11-30 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20200905_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False)),
                ('dttm_sent', models.DateTimeField()),
                ('alert_type', models.CharField(choices=[('CT', 'предстоящая тренировка')], default='CT', max_length=2)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tr_day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.GroupTrainingDay')),
            ],
        ),
        migrations.AlterField(
            model_name='traininggroup',
            name='level',
            field=models.CharField(choices=[('G', '🍏зелёный мяч🍏'), ('O', '\U0001f9e1оранжевый мяч\U0001f9e1')], default='O', max_length=1, verbose_name='Уровень группы'),
        ),
    ]
