# Generated by Django 2.0.5 on 2020-11-30 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20201130_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertslog',
            name='dttm_sent',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 13, 40, 23, 574879)),
        ),
    ]
