# Generated by Django 3.2.12 on 2023-05-25 11:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0024_auto_20230507_2205"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grouptrainingday",
            name="is_available",
        ),
    ]
