# Generated by Django 3.2.12 on 2023-05-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0026_cancel"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cancel",
            new_name="PlayerCancelLesson",
        ),
        migrations.AddField(
            model_name="player",
            name="n_cancelled_lessons",
            field=models.SmallIntegerField(default=0, verbose_name="Количество отмен"),
        ),
    ]
