# Generated by Django 2.0.5 on 2020-12-07 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20201130_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertslog',
            name='info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='alertslog',
            name='dttm_sent',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 16, 10, 6, 181965)),
        ),
    ]
