# Generated by Django 2.0.5 on 2021-01-04 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_20201207_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertslog',
            name='alert_type',
            field=models.CharField(choices=[('CT', 'предстоящая тренировка'), ('CM', 'сообщение от тренера')], default='CT', max_length=2),
        ),
        migrations.AlterField(
            model_name='alertslog',
            name='dttm_sent',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 7, 41, 7, 84237)),
        ),
    ]
