# Generated by Django 2.0.5 on 2021-01-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_auto_20210104_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertslog',
            name='alert_type',
            field=models.CharField(choices=[('CT', 'предстоящая тренировка'), ('CM', 'сообщение от тренера'), ('SP', 'нужно заплатить за месяц')], default='CT', max_length=2),
        ),
    ]
