# Generated by Django 2.0.5 on 2021-01-12 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_auto_20210112_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertslog',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Payment'),
        ),
    ]
