# Generated by Django 2.0.5 on 2021-01-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_alertslog_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininggroup',
            name='available_for_additional_lessons',
            field=models.BooleanField(default=False, help_text='Можно ли прийти в эту группу на занятия за деньги,если меньше, чем max_players', verbose_name='Занятия за деньги'),
        ),
    ]
