# Generated by Django 2.0.5 on 2021-01-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_grouptrainingday_pay_visitors'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticdata',
            name='tarif_payment_add_lesson',
            field=models.PositiveIntegerField(default=100, null=True, verbose_name='Стоимость, если отыгрывает платно'),
        ),
    ]
