SHOW_GROUPDAY_INFO = "GROUPDAY_INFO"
CLNDR_ADMIN_VIEW_SCHEDULE = "VIEW_SCHEDULE"
AVAILABLE_TRAIN_DAY_ACTION_CONFIRM = "AVAILABLE_ACTION_CONFIRM"
AVAILABLE_TRAIN_DAY_ACTION = "AVAILABLE_TRAIN_DAY_ACTION"
