on:
  workflow_run:
    workflows: ["deploy"]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Success alert
      env:
        ALERTING_TELEGRAM_TOKEN: ${{ secrets.ALERTING_TELEGRAM_TOKEN }}
        TEXT: Successfully_deployed
        LOG_CHAT_ID: 350490234
      run: |
        echo "${TEXT}" && curl -X GET "https://api.telegram.org/bot$ALERTING_TELEGRAM_TOKEN/sendMessage?chat_id=$LOG_CHAT_ID&text=$TEXT"
